Remove peripheralId from SimulatedService
Polidea/blemulator_flutter pull request #7
Opened 2019-10-25 16:40 UTC by mikolak

Resolves https://github.com/Polidea/FlutterBleLib/issues/276

2019-10-28 10:28 UTC, pawelByszewski commented
What about starting introducing some unit tests in changed areas?

2019-10-28 14:32 UTC, bartoszwilk submitted a review, later dismissed

2019-10-28 14:32 UTC, bartoszwilk commented on lib/internal/simulation_manager_mixins/characteristics_mixin.dart
> +    await _errorIfNotConnected(_peripheralWithServiceId(serviceIdentifier).id);
_findPeripheralWithServiceId? _findPeripheralForServiceId? _getPeripheralForServiceId?

2019-10-28 14:32 UTC, bartoszwilk commented on lib/internal/simulation_manager_mixins/characteristics_mixin.dart
> +              _peripheralWithCharacteristicId(characteristicIdentifier).id,
_findPeripheralWithCharacteristicId? _findPeripheralForCharacteristicId? _getPeripheralForCharacteristicId?

2019-10-30 09:01 UTC, pawelByszewski requested changes
What about starting introducing some unit tests in changed areas?

2019-11-07 09:20 UTC, pawelByszewski approved these changes

2019-11-07 09:20 UTC, merged